FROM centos
RUN yum install epel-release -y
RUN yum install httpd -y
COPY homedecor.html /root
RUN chmod 755 /root/homedecor.html
RUN mv -f /root/homedecor.html /var/www/html/index.html
ENTRYPOINT service httpd start && /bin/bash
