FROM centos
RUN yum install epel-release -y
COPY apache.sh /root
COPY homedecor.html /root
RUN chmod 755 /root/homedecor.html
RUN chmod 755 /root/apache.sh
CMD /root/apache.sh
RUN mv -f /root/homedecor.html /var/www/html
ENTRYPOINT service httpd start && /bin/bash
